<a href="https://colab.research.google.com/github/ShounakD1991/UDEMY_MACHINE_LEARNING_A-Z_HANDS_ON_PYTHON_IN_DATA_SCIENCE/blob/main/Data_Preprocessing_14_02_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive




---
## Data Preprocessing Tools
---







---
### Importing Libraries
---







In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns



---
### Importing Dataset
---





In [ ]:
df=pd.read_csv("/content/drive/MyDrive/PGDSE_STUDY_MATERIAL/Udemy Courses/Machine Learning A-Z Hands-On Python & R In Data Science/Part 1 - Data Preprocessing/Section 2 -------------------- Part 1 - Data Preprocessing --------------------/Python/Data.csv")
print(df)
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']




---
### Taking care of Missing Data
---





In [ ]:
from sklearn.impute import SimpleImputer
imputer= SimpleImputer(missing_values=np.nan,strategy='mean')
x[:,1:3]=imputer.fit_transform(x[:,1:3])

In [ ]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)



---
### Encoding Categorical Data
---







---
#### Encoding Independent Variable
---





In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]




---
#### Encoding dependent Variable
---





In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]




---
We have to apply feature scaling after splitting the dataset 
into the training set and a test set and now let me explain.
Splitting the dataset into the training set in a test consists of making two separate sets. One training set where you're going to train your missionary model on existing observations and one test set where you're going to evaluate the performance of your model on new observations.

And it's important to understand that these new observations are exactly like you know some future data that you're going to get and on which you're going to deploy your machine learning model.

So that's this first tool and now feature scaling simply consists of scaling all your variables or your features actually to make sure they all take values in the same scale.

And we do this so as to prevent one feature to dominate the other which therefore would be neglected by the machine learning model.

We have to apply feature scaling after splitting the data set into the training set and instead it's really obvious it is for the simple reason that the test set is supposed to be a brand new set on which you are going to evaluate your machine learning model.

So it's exactly like you know you're training your machinery moral on your training set and then later on you know after it is trained you are going to deploy it on new observations.

So what this means is that the test set is something you're not supposed to work with for the training and features killing is as you will see a technique that will get the mean and standard deviation of your feature.

You know in order to perform the scaling.

So if we apply feature scaling before the split then it will actually get the mean and standard deviation of all the values including the ones in the test set and since the test set is something you're not supposed to have you know like some future data in production.

Well you know applying pictures killing on the original day you said before the split would cause some what we call information leakage on the test set.

You know we would grab some information from the test set which we're not supposed to get because it is supposed to be new data with new observations.

So remember this the essential reason why you should not apply features scaling before the split is to prevent information leakage on the test set which you're not supposed to have until the training
---







---
### Splitting the dataset into the Training and Test set
---





In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=101)

In [ ]:
X_train

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0]], dtype=object)

In [ ]:
X_test

array([[0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0]], dtype=object)

In [ ]:
y_train

array([0, 1, 1, 0, 1, 1, 0, 1])

In [ ]:
y_test

array([0, 0])

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:,3:]=sc.fit_transform(X_train[:,3:])
X_test[:,3:]=sc.fit_transform(X_test[:,3:])

In [ ]:
X_train

array([[1.0, 0.0, 0.0, 0.951826310201807, 0.9861483502652316],
       [0.0, 1.0, 0.0, 0.2630675731713538, 0.1238147854838185],
       [1.0, 0.0, 0.0, -0.2535014796014861, 0.4617563176278856],
       [0.0, 0.0, 1.0, -0.08131179534387281, -0.16751412153692966],
       [1.0, 0.0, 0.0, -0.5978808481167127, -0.48214934111933727],
       [1.0, 0.0, 0.0, 1.6405850472322603, 1.7202971959575162],
       [0.0, 0.0, 1.0, 0.052613514634271004, -1.1114197802841526],
       [0.0, 0.0, 1.0, -1.9753983221776192, -1.5309334063940294]],
      dtype=object)

In [ ]:
X_test

array([[0.0, 1.0, 0.0, 1.0, 1.0],
       [0.0, 1.0, 0.0, -1.0, -1.0]], dtype=object)